Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pv_data['ratio'] = center_gender.ratio.values
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m<ipython-input-43-aca549eb7c4a>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mpv_data[0m[0;34m[[0m[0;34m'ratio'[0m[0;34m][0m [0;34m=[0m [0mcenter_gender[0m[0;34m.[0m[0mratio[0m[0;34m.[0m[0mvalues[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py[0m in [0;36m__setitem__[0;34m(self, key, value)[0m
[1;32m   3161[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   3162[0m             [0;31m# set column[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 3163[0;31m             [0mself[0m[0;34m.[0m[0m_set_item[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0mvalue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3164[0m [0;34m[0m[0m
[1;32m   3165[0m     [0;32mdef[0m [0m_setitem_slice[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mkey[0m[0;34m:[0m [0mslice[0m[0;34m,[0m [0mvalue[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py[0m in [0;36m_set_item[0;34m(self, key, value)[0m
[1;32m   3237[0m         """
[1;32m   3238[0m         [0mself[0m[0;34m.[0m[0m_ensure_valid_index[0m[0;34m([0m[0mvalue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 3239[0;31m         [0mvalue[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_sanitize_column[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0mvalue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3240[0m         [0mNDFrame[0m[0;34m.[0m[0m_set_item[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mkey[0m[0;34m,[0m [0mvalue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   3241[0m [0;34m[0m[0m

[0;32m/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py[0m in [0;36m_sanitize_column[0;34m(self, key, value, broadcast)[0m
[1;32m   3894[0m [0;34m[0m[0m
[1;32m   3895[0m             [0;31m# turn me into an ndarray[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 3896[0;31m             [0mvalue[0m [0;34m=[0m [0msanitize_index[0m[0;34m([0m[0mvalue[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mindex[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3897[0m             [0;32mif[0m [0;32mnot[0m [0misinstance[0m[0;34m([0m[0mvalue[0m[0;34m,[0m [0;34m([0m[0mnp[0m[0;34m.[0m[0mndarray[0m[0;34m,[0m [0mIndex[0m[0;34m)[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   3898[0m                 [0;32mif[0m [0misinstance[0m[0;34m([0m[0mvalue[0m[0;34m,[0m [0mlist[0m[0;34m)[0m [0;32mand[0m [0mlen[0m[0;34m([0m[0mvalue[0m[0;34m)[0m [0;34m>[0m [0;36m0[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/internals/construction.py[0m in [0;36msanitize_index[0;34m(data, index)[0m
[1;32m    749[0m     """
[1;32m    750[0m     [0;32mif[0m [0mlen[0m[0;34m([0m[0mdata[0m[0;34m)[0m [0;34m!=[0m [0mlen[0m[0;34m([0m[0mindex[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 751[0;31m         raise ValueError(
[0m[1;32m    752[0m             [0;34m"Length of values "[0m[0;34m[0m[0;34m[0m[0m
[1;32m    753[0m             [0;34mf"({len(data)}) "[0m[0;34m[0m[0;34m[0m[0m

[0;31mValueError[0m: Length of values (24) does not match length of index (23)
ValueError: Length of values (24) does not match length of index (23)

